name: SvelteKit CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24" # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build SvelteKit application
        run: npm run build # This will create the production build in the 'build' or 'dist' directory
