name: SvelteKit CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install Trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      - name: Build shellcide
        run: |
          cd shellcide
          trunk build --release --public-url /projects/shellcide/

      - name: Move shellcide build to static/projects/shellcide
        run: |
          mkdir -p static/projects/shellcide
          rm -rf static/projects/shellcide/*
          cp -R shellcide/dist/* static/projects/shellcide/

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24" # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Install wasm-bindgen-cli
        uses: jetli/wasm-bindgen-action@v0.2.0
        with:
          version: "0.2.122"

      - name: Build pbkdf2-identifier
        run: |
          cd pbkdf2-identifier/gui
          npm install
          npm run build -- --base=/projects/pbkdf2-identifier/

      - name: Move pbkdf2-identifier build to static/projects/pbkdf2-identifier
        run: |
          mkdir -p static/projects/pbkdf2-identifier
          rm -rf static/projects/pbkdf2-identifier/*
          cp -R pbkdf2-identifier/gui/dist/* static/projects/pbkdf2-identifier/

      - name: Build SvelteKit application
        run: npm run build # This will create the production build in the 'build' or 'dist' directory
